package profile

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/projectseven-co-ltd/p7-scanner/tools/signalforge-cli/internal/recorder"
)

const (
	dirName      = "signalforge"
	profileName  = "profile.json"
	recorderName = "config.toml"
)

type FolderIngest struct {
	Enabled            bool   `json:"enabled"`
	Directory          string `json:"directory"`
	ProcessedDirectory string `json:"processedDirectory"`
	ReprocessProcessed bool   `json:"reprocessProcessed"`
	PollMs             int    `json:"pollMs"`
	StableMs           int    `json:"stableMs"`
}

type Canary struct {
	Enabled        bool   `json:"enabled"`
	IntervalSec    int    `json:"intervalSec"`
	Talkgroup      int    `json:"talkgroup,omitempty"`
	TalkgroupLabel string `json:"talkgroupLabel,omitempty"`
}

type Profile struct {
	HubURL     string             `json:"hubUrl"`
	SourceKey  string             `json:"sourceKey,omitempty"`
	TimeoutSec int                `json:"timeoutSec"`
	Folder     FolderIngest       `json:"folderIngest"`
	Canary     Canary             `json:"canary"`
	Metadata   recorder.Metadata  `json:"metadata"`
}

func Default() Profile {
	settings := recorder.DefaultSettings()
	return Profile{
		TimeoutSec: 20,
		Folder: FolderIngest{
			Enabled:            true,
			ProcessedDirectory: "processed",
			PollMs:             int(settings.Poll / time.Millisecond),
			StableMs:           int(settings.Stable / time.Millisecond),
		},
		Canary: Canary{
			IntervalSec: 300,
		},
		Metadata: settings.Metadata,
	}
}

func Dir() (string, error) {
	base, err := configBaseDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(base, dirName), nil
}

func configBaseDir() (string, error) {
	if xdg := strings.TrimSpace(os.Getenv("XDG_CONFIG_HOME")); xdg != "" {
		return xdg, nil
	}
	return os.UserConfigDir()
}

func Path() (string, error) {
	dir, err := Dir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, profileName), nil
}

func RecorderTOMLPath() (string, error) {
	dir, err := Dir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, recorderName), nil
}

func Load() (Profile, error) {
	path, err := Path()
	if err != nil {
		return Profile{}, err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return Profile{}, err
	}
	var profile Profile
	if err := json.Unmarshal(data, &profile); err != nil {
		return Profile{}, fmt.Errorf("parse profile: %w", err)
	}
	return profile, nil
}

func Save(profile Profile) (string, error) {
	dir, err := Dir()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	path := filepath.Join(dir, profileName)
	data, err := json.MarshalIndent(profile, "", "  ")
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return "", err
	}
	tomlPath := filepath.Join(dir, recorderName)
	if err := os.WriteFile(tomlPath, []byte(RenderRecorderTOML(profile)), 0o600); err != nil {
		return "", err
	}
	envPath := filepath.Join(dir, "env")
	if err := os.WriteFile(envPath, []byte(RenderEnv(profile)), 0o600); err != nil {
		return "", err
	}
	return path, nil
}

func (p Profile) ToRecorderSettings() recorder.Settings {
	settings := recorder.DefaultSettings()
	if p.Folder.Directory != "" {
		settings.Input = p.Folder.Directory
	}
	if p.Folder.ProcessedDirectory != "" {
		settings.Processed = p.Folder.ProcessedDirectory
	}
	if p.Folder.PollMs > 0 {
		settings.Poll = time.Duration(p.Folder.PollMs) * time.Millisecond
	}
	if p.Folder.StableMs > 0 {
		settings.Stable = time.Duration(p.Folder.StableMs) * time.Millisecond
	}
	settings.Reprocess = p.Folder.ReprocessProcessed
	settings.Metadata = p.Metadata
	canaryInterval := time.Duration(p.Canary.IntervalSec) * time.Second
	if p.Canary.IntervalSec <= 0 {
		canaryInterval = 5 * time.Minute
	}
	settings.Canary = recorder.CanarySettings{
		Enabled:        p.Canary.Enabled,
		Interval:       recorder.NormalizeCanaryInterval(canaryInterval),
		Talkgroup:      p.Canary.Talkgroup,
		TalkgroupLabel: p.Canary.TalkgroupLabel,
	}
	return settings
}

func RenderEnv(p Profile) string {
	lines := []string{
		"# Generated by: sf onboard",
		fmt.Sprintf("SIGNALFORGE_HUB_URL=%s", p.HubURL),
	}
	if strings.TrimSpace(p.SourceKey) != "" {
		lines = append(lines, fmt.Sprintf("SIGNALFORGE_SOURCE_KEY=%s", p.SourceKey))
	}
	return strings.Join(lines, "\n") + "\n"
}

func RenderRecorderTOML(p Profile) string {
	meta := p.Metadata
	if meta.System == 0 {
		meta = recorder.DefaultSettings().Metadata
	}
	timeout := p.TimeoutSec
	if timeout <= 0 {
		timeout = 20
	}
	interval := p.Canary.IntervalSec
	if interval <= 0 {
		interval = 300
	}
	poll := p.Folder.PollMs
	if poll <= 0 {
		poll = 1000
	}
	stable := p.Folder.StableMs
	if stable <= 0 {
		stable = 2500
	}
	processed := p.Folder.ProcessedDirectory
	if processed == "" {
		processed = "processed"
	}
	dir := p.Folder.Directory
	if dir == "" {
		dir = "ingest"
	}

	canaryTG := ""
	if p.Canary.Talkgroup > 0 {
		canaryTG = fmt.Sprintf("talkgroup = %d\n", p.Canary.Talkgroup)
	}
	canaryLabel := ""
	if strings.TrimSpace(p.Canary.TalkgroupLabel) != "" {
		canaryLabel = fmt.Sprintf("talkgroup_label = %q\n", p.Canary.TalkgroupLabel)
	}

	return fmt.Sprintf(`# Generated by: sf onboard
[p7]
base_url = %q
source_key = %q
timeout_sec = %d

[metadata]
system = %d
system_label = %q
talkgroup = %d
talkgroup_label = %q
talkgroup_group = %q
talkgroup_tag = %q
frequency = %d

[folder_ingest]
enabled = %t
directory = %q
processed_directory = %q
reprocess_processed = %t
poll_ms = %d
stable_ms = %d

[canary]
enabled = %t
interval_sec = %d
%s%s
`,
		strings.TrimRight(p.HubURL, "/")+"/",
		p.SourceKey,
		timeout,
		meta.System,
		meta.SystemLabel,
		meta.Talkgroup,
		meta.TalkgroupLabel,
		meta.TalkgroupGroup,
		meta.TalkgroupTag,
		meta.Frequency,
		p.Folder.Enabled,
		dir,
		processed,
		p.Folder.ReprocessProcessed,
		poll,
		stable,
		p.Canary.Enabled,
		interval,
		canaryTG,
		canaryLabel,
	)
}
