// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadConfig(arg1) {
  return window['go']['main']['App']['LoadConfig'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartRecorder(arg1) {
  return window['go']['main']['App']['StartRecorder'](arg1);
}

export function StopRecorder() {
  return window['go']['main']['App']['StopRecorder']();
}
