// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetVersion():Promise<string>;

export function ListDevices():Promise<string>;

export function LoadConfig(arg1:string):Promise<main.RecorderConfig>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.RecorderConfig):Promise<void>;

export function StartRecorder(arg1:main.RecorderConfig):Promise<void>;

export function StopRecorder():Promise<void>;
