#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH= cd -- "$script_dir/.." && pwd)
output_file="$repo_dir/.env.production"
force=0
yes=0

usage() {
  cat <<'USAGE'
Usage: tools/init-env.sh [options]

Create a .env.production file for the Docker Compose install path.

Options:
  --output FILE   Write to FILE instead of .env.production
  --force         Overwrite the output file if it already exists
  --yes           Use defaults and environment variables without prompting
  -h, --help      Show this help

Environment overrides:
  SIGNALFORGE_PUBLIC_URL, SIGNALFORGE_HUB_NAME, SIGNALFORGE_HUB_REGION,
  SIGNALFORGE_HUB_CONTACT, SIGNALFORGE_IMAGE_TAG, POSTGRES_PASSWORD,
  MAILJET_API_KEY, MAILJET_SECRET_KEY, MAIL_FROM_EMAIL, MAIL_FROM_NAME,
  CLIENT_PORT, SERVER_PORT
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --output)
      [ "$#" -ge 2 ] || { echo "Missing value for --output" >&2; exit 2; }
      output_file="$2"
      shift 2
      ;;
    --force)
      force=1
      shift
      ;;
    --yes)
      yes=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

ask() {
  label="$1"
  default_value="$2"

  if [ "$yes" -eq 1 ]; then
    printf '%s\n' "$default_value"
    return
  fi

  if [ -n "$default_value" ]; then
    printf '%s [%s]: ' "$label" "$default_value" >&2
  else
    printf '%s: ' "$label" >&2
  fi

  IFS= read -r answer || answer=""
  if [ -n "$answer" ]; then
    printf '%s\n' "$answer"
  else
    printf '%s\n' "$default_value"
  fi
}

generate_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
    return
  fi

  date "+signalforge-%Y%m%d%H%M%S"
}

strip_trailing_slash() {
  printf '%s' "$1" | sed 's#/*$##'
}

host_from_url() {
  printf '%s' "$1" | sed -E 's#^https?://##; s#/.*$##; s/:.*$//'
}

slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-//; s/-$//'
}

if [ -e "$output_file" ] && [ "$force" -ne 1 ]; then
  echo "$output_file already exists. Re-run with --force to overwrite it." >&2
  exit 1
fi

default_url=${SIGNALFORGE_PUBLIC_URL:-https://scanner.example.com}
public_url=$(strip_trailing_slash "$(ask "Public hub URL" "$default_url")")

case "$public_url" in
  http://*|https://*) ;;
  *)
    echo "Public hub URL must start with http:// or https://" >&2
    exit 1
    ;;
esac

public_host=$(host_from_url "$public_url")
default_stack_id=$(slugify "$public_host")
[ -n "$default_stack_id" ] || default_stack_id="signalforge-hub"

hub_name=$(ask "Hub display name" "${SIGNALFORGE_HUB_NAME:-SignalForge Hub}")
hub_region=$(ask "Hub region/area (optional)" "${SIGNALFORGE_HUB_REGION:-}")
hub_contact=$(ask "Hub contact email or URL (optional)" "${SIGNALFORGE_HUB_CONTACT:-}")
image_tag=$(ask "Image tag" "${SIGNALFORGE_IMAGE_TAG:-latest}")
client_port=$(ask "Host web port" "${CLIENT_PORT:-3000}")
server_port=$(ask "Host API port" "${SERVER_PORT:-8080}")

default_mail_from="no-reply@$public_host"
mail_from_email=$(ask "Mail-from email" "${MAIL_FROM_EMAIL:-$default_mail_from}")
mail_from_name=$(ask "Mail-from name" "${MAIL_FROM_NAME:-$hub_name}")
mailjet_api_key=$(ask "Mailjet API key (optional for now)" "${MAILJET_API_KEY:-}")
mailjet_secret_key=$(ask "Mailjet secret key (optional for now)" "${MAILJET_SECRET_KEY:-}")

postgres_password=${POSTGRES_PASSWORD:-$(generate_password)}

mkdir -p "$(dirname -- "$output_file")"
tmp_file="$output_file.tmp.$$"
trap 'rm -f "$tmp_file"' EXIT HUP INT TERM

cat > "$tmp_file" <<ENV
# Generated by tools/init-env.sh

# Published SignalForge images
IMAGE_REGISTRY=ghcr.io
IMAGE_NAMESPACE=signalforge-org
IMAGE_TAG=$image_tag
STACK_ID=$default_stack_id

# Runtime config
APP_ENV=production
LOG_LEVEL=info
APP_BASE_URL=$public_url
UPDATE_CHECK_URL=https://signalforge.org/p7-scanner-update.json

# SignalHub identity and federation
HUB_NAME=$hub_name
HUB_PUBLIC_URL=$public_url
HUB_REGION=$hub_region
HUB_CONTACT=$hub_contact
HUB_FEDERATION_ENABLED=false
HUB_TRUST_LEVEL=community
HUB_TRUST_ISSUER=
HUB_TRUST_CERTIFICATE=
HUB_TRUST_EXPIRES_AT=0
HUB_DIRECTORY_URL=https://signalforge.org/directory/hubs.json

# Magic-link email delivery through Mailjet
MAILJET_API_KEY=$mailjet_api_key
MAILJET_SECRET_KEY=$mailjet_secret_key
MAIL_FROM_EMAIL=$mail_from_email
MAIL_FROM_NAME=$mail_from_name

# Mock sender target
SCANNER_URL=$public_url

# Bundled PostgreSQL service
POSTGRES_DB=p7scanner
POSTGRES_USER=p7scanner
POSTGRES_PASSWORD=$postgres_password

# Host ports
SERVER_PORT=$server_port
CLIENT_PORT=$client_port

# Mock call sender, only used with --profile mock
MOCK_INTERVAL_SEC=5
MOCK_DURATION_SEC=3
MOCK_SYSTEM_ID=1
MOCK_SYSTEM_LABEL=Mock P25 System
MOCK_FREQUENCY=460000000
MOCK_SOURCE_API_KEY=
ENV

mv "$tmp_file" "$output_file"
chmod 600 "$output_file"
trap - EXIT HUP INT TERM

cat <<NEXT

Wrote $output_file

Next steps:
  docker compose --env-file $output_file -f docker-compose.prod.yml up -d
  curl http://localhost:$server_port/api/v1/health

Point HTTPS for $public_url at host port $client_port.
NEXT